name: Static Application Security Testing

on:
  push:
    branches: [test-ci]
  pull_request:
    branches: [test-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with maven and run SpotBugs
        run: mvn clean install spotbugs:spotbugs
      - name: Publish SpotBugs report
        uses: jwgmeligmeyling/spotbugs-github-action@v1
        with:
          path: '**/spotbugsXml.xml'